### ISSUE TITLE
error deploying the plugin using cli command 

### ISSUE THREAD

**Issue by shashanksal** [twilio-labs/plugin-flex#68]
I am trying to migrate my existing plugins to the new plugin API.
I have successfully managed to migrate two of my existing plugins. I am facing an issue with my third plugin that is comparatively larger in size when built (536 Kb)
When I try to use the command 
`UNBUNDLED_REACT=true twilio flex:plugins:deploy --changelog "Migration from v3 to v4" --description "My Desctiption"`

My plugin compiles with warnings but never finishes the upload.

> 
<img width="1122" alt="Screen Shot 2020-10-28 at 2 27 12 pm" src="https://user-images.githubusercontent.com/53556855/97387446-1ebdad00-192a-11eb-89a7-30c3260a45ff.png">

So as a quick investigation, I tried running the build command
`UNBUNDLED_REACT=true twilio flex:plugins:build`

Which showed me the webpack warnings

```Using profile XXXX XXXXX XXXX (ACXXXXXXXXXXXXXXXXXXX)

Compiling a production build...

Plugin plugin-myplugin was successfully compiled with some warnings.

Warning 1
asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  plugin-myplugin.js (536 KiB)
Warning 2
entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (536 KiB)
      plugin-myplugin.js

Warning 3
webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

3 'files were compiled:'
         535.5 KB        build/plugin-myplugin.js
         2.2 KB          build/plugin-myplugin.js.LICENSE.txt
         0.1 KB          build/plugin-myplugin.js.map
```

Is there a way I can resolve this?

**Comment by ktalebian** [comment]
@shashanksal it looks like your CLI is stuck on `Uploading plugin-*` step. I just tried uploading a 800kb plugin; it took a while but it did upload eventually. 

How long did you wait on this step before giving up? It looks like it's just taking a long time to upload because of the size of the plugin (what's your internet upload speed?)

For comparison, can you somehow make this file smaller and see if you still having issues?

**Comment by shashanksal** [comment]
@ktalebian , I have a decent upload speed(15-20 Mbps). I have tried uploading this plugin for close to 20+ minutes and I still couldn't upload it. 
I have succesfully uploaded my other plugin (310 Kb) in a matter or few seconds. 

I have already stripped my plugin from original 910Kb to the current size. I guess I wouldn't be able to make it more smaller than this unless I figure out a way to reduce my library imports. 

Btw, are library imports responsible for the size?
I have a few dependecies installed. Does that affects the upload ? 
```
"dependencies": {
    "@emotion/core": "^10.0.35",
    "@emotion/styled": "^10.0.27",
    "@material-ui/core": "^3.9.4",
    "export-to-csv": "^0.2.1",
    "flex-plugin": "4.0.2-beta.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-flatpickr": "^3.10.6",
    "react-md-spinner": "^1.0.0",
    "react-user-avatar": "^1.10.0",
    "socket.io": "^2.3.0"
  }
```

**Comment by shashanksal** [comment]
Any update on this?

**Comment by ktalebian** [comment]
@shashanksal apologies for dropping the ball on this. Please update to the latest version of the plugin-builder by running the following two commands:

```
twilio plugins:update

# Confirm you have the latest version by running `twilio plugins`; it should show `1.2.8-beta.0` as the version

# Run this in the plugin's directory
twilio flex:plugins:upgrade-plugin --yes --beta --install
```

Then redeploy but this with the `DEBUG=true` flag:

```
DEBUG=true twilio flex:plugins:deploy --changelog "YOUR CHANGE LOG"
```

This time in the debug mode, when it gets to the upload stage, there should be a progress update, something like
```
Uploading 0.3% complete
Uploading 0.4% complete
Uploading 0.4% complete
Uploading 0.7% complete
Uploading 0.7% complete
Uploading 0.7% complete
Uploading 1.2% complete
Uploading 99.8% complete
Uploading 100.0% complete
```

Can you dump the output of the terminal after this and let's see where your deployment is pausing at.

**Comment by shashanksal** [comment]
The issue is resolved now. 
I think was to do with `plugin:update`. 
Although I was running twilio-cli@2.13.0 , i didn't realize I needed to update my plugins API. 
Now it's done and I am able to upload the plugin.

Thanks for your help.

I think we can close the issue now.
