### ISSUE TITLE
Error creating new plugin - Cannot find module '@k88/pipe-compose'

### ISSUE THREAD

**Issue by andrucz** [twilio-labs/plugin-flex#79]
**Steps to reproduce:**

Install Twilio CLI globally:
`$ npm install twilio-cli@latest -g`

Install the CLI Flex plugin:
`$ twilio plugins:install @twilio-labs/plugin-flex@beta`

Create a new Typescript plugin:
`$ twilio flex:plugins:create plugin-sample1 --install --typescript`

Result:
- Creating project directory
√ Creating project directory
- Installing dependencies
× Command failed with ENOENT: npm install
spawn npm ENOENT
npm WARN deprecated react-router-redux@5.0.0-alpha.9: This project is no longer maintained.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated cheerio-select-tmp@0.1.1: Use cheerio-select instead
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
C:\Users\andru\Documents\temp\ff\plugin-sample1\node_modules\flex-plugins-utils-logger\dist\lib\logger.js:1
**Error: Cannot find module '@k88/pipe-compose'. Please verify that the package.json has a valid "main" entry**
    at Object.<anonymous> (C:\Users\andru\Documents\temp\ff\plugin-sample1\node_modules\flex-plugins-utils-logger\dist\lib\logger.js:30:22) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\andru\\Documents\\temp\\ff\\plugin-sample1\\node_modules\\@k88\\pipe-compose\\package.json',
  requestPath: '@k88/pipe-compose'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plugin-sample1@0.0.0 postinstall: `flex-plugin pre-script-check`
npm ERR! Exit status 1

**Comment by ktalebian** [comment]
@andrucz apologize about this - this is now fixed. Please remove `node_modules` and re-run `npm install` and this should be fixed.
