### ISSUE TITLE
Flex Plugin Installation Issues

### ISSUE THREAD

**Issue by joshuaremer** [twilio-labs/plugin-flex#81]
**End Result:** I'm trying to create a CRM integration into Twilio Flex. The CRM is a built-from-scratch platform. There are several ways I could go about solving the issue: 1. Pass gathered variables captured in my Studio IVR to the Customer Context section of Flex so the agent gets the necessary information to look up the customer in the CRM without having to request the account information a second time 2. Create a screen pop when the agent answers a flex call/text/chat that would bring up the correct customer screen based on a URL with the account number variables at the end that were entered in the IVR/text/chat.

I would prefer to create the 2nd option of a screen pop to be integrated into the CRM section of Flex so that the agent doesn't need to enter in details that were already captured in the IVR/text/chat, but I have limited developing experience and that option is appearing to be a more complex solution.

**Current Issue:** My current issue however, is related to building a plugin for Flex. I currently am going through the Twilio instructions and am having an issue with getting a sample environment Started. I downloaded node v15.7.0 and npm v7.4.3 and am currently walking through the steps provided here: https://www.twilio.com/docs/flex/quickstart/getting-started-plugin I just tried to run twilio flex:plugins:create plugin-sample --install and got the following error. I'm hoping someone can provide some insight on how to fix it.

C:\Users\joshr>twilio flex:plugins:create plugin-sample --install
√ Creating project directory
× Command failed with exit code 1: npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @material-ui/core@3.9.3
npm WARN node_modules/@material-ui/core
npm WARN   @material-ui/core@"3.9.3" from @twilio/flex-ui@1.24.2
npm WARN   node_modules/@twilio/flex-ui
npm WARN     dev @twilio/flex-ui@"^1" from the root project
npm WARN   2 more (@material-ui/lab, @twilio/flex-ui-core)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @material-ui/core@"^1.0.0" from @material-ui/icons@2.0.3
npm WARN node_modules/@material-ui/icons
npm WARN   @material-ui/icons@"2.0.3" from @twilio/flex-ui-core@0.47.2
npm WARN   node_modules/@twilio/flex-ui-core
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@16.5.2
npm ERR! node_modules/react
npm ERR!   react@"16.5.2" from the root project
npm ERR!   react@"^16.5.2" from @twilio/flex-ui@1.24.2
npm ERR!   node_modules/@twilio/flex-ui
npm ERR!     dev @twilio/flex-ui@"^1" from the root project
npm ERR!   4 more (react-dom, @material-ui/core, @material-ui/lab, @twilio/flex-ui-core)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.14.0" from react-test-renderer@16.14.0
npm ERR! node_modules/enzyme-adapter-react-16/node_modules/react-test-renderer
npm ERR!   react-test-renderer@"^16.0.0-0" from enzyme-adapter-react-16@1.15.6
npm ERR!   node_modules/enzyme-adapter-react-16
npm ERR!     enzyme-adapter-react-16@"^1" from flex-plugin-test@4.3.18-beta.0
npm ERR!     node_modules/flex-plugin-test
npm ERR!       flex-plugin-test@"^4.3.18-beta.0" from flex-plugin-scripts@4.3.18-beta.0
npm ERR!       node_modules/flex-plugin-scripts
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\joshr\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joshr\AppData\Local\npm-cache\_logs\2021-01-27T20_01_09_372Z-debug.log
Error: Command failed with exit code 1: npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @material-ui/core@3.9.3
npm WARN node_modules/@material-ui/core
npm WARN   @material-ui/core@"3.9.3" from @twilio/flex-ui@1.24.2
npm WARN   node_modules/@twilio/flex-ui
npm WARN     dev @twilio/flex-ui@"^1" from the root project
npm WARN   2 more (@material-ui/lab, @twilio/flex-ui-core)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @material-ui/core@"^1.0.0" from @material-ui/icons@2.0.3
npm WARN node_modules/@material-ui/icons
npm WARN   @material-ui/icons@"2.0.3" from @twilio/flex-ui-core@0.47.2
npm WARN   node_modules/@twilio/flex-ui-core
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@16.5.2
npm ERR! node_modules/react
npm ERR!   react@"16.5.2" from the root project
npm ERR!   react@"^16.5.2" from @twilio/flex-ui@1.24.2
npm ERR!   node_modules/@twilio/flex-ui
npm ERR!     dev @twilio/flex-ui@"^1" from the root project
npm ERR!   4 more (react-dom, @material-ui/core, @material-ui/lab, @twilio/flex-ui-core)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.14.0" from react-test-renderer@16.14.0
npm ERR! node_modules/enzyme-adapter-react-16/node_modules/react-test-renderer
npm ERR!   react-test-renderer@"^16.0.0-0" from enzyme-adapter-react-16@1.15.6
npm ERR!   node_modules/enzyme-adapter-react-16
npm ERR!     enzyme-adapter-react-16@"^1" from flex-plugin-test@4.3.18-beta.0
npm ERR!     node_modules/flex-plugin-test
npm ERR!       flex-plugin-test@"^4.3.18-beta.0" from flex-plugin-scripts@4.3.18-beta.0
npm ERR!       node_modules/flex-plugin-scripts
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with force, or legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:UsersjoshrAppDataLocalnpm-cacheeresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:UsersjoshrAppDataLocalnpm-cache_logs2021-01-27T20_01_09_372Z-debug.log
    at C:Usersjoshr.twilio-clinode_modulescreate-flex-plugindistlibcommands.js:86:27
    at step (C:Usersjoshr.twilio-clinode_modulescreate-flex-plugindistlibcommands.js:52:23)
    at Object.next (C:Usersjoshr.twilio-clinode_modulescreate-flex-plugindistlibcommands.js:33:53)
    at fulfilled (C:Usersjoshr.twilio-clinode_modulescreate-flex-plugindistlibcommands.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by ktalebian** [comment]
@joshuaremer we do not recommend using Node 15/npm 7; please either downgrade to Node 14 (generally, using even number of Node is recommended since odd versions of Node will never become LTS), or if you want to use Node 15, then see https://github.com/twilio/flex-plugin-builder/blob/v4-beta/faq.md#npm-install-fails-on-npm-7

**Comment by joshuaremer** [comment]
@ktalebian That worked. Ty.

**Comment by ktalebian** [comment]
Glad to hear that :)
